# 유형 22 : 리스트를 품은 딕셔너리 형태로 데이터 저장하기

## 읽기 영역

### 문제 01
아래 코드를 읽고 출력 결과를 맞춰보세요

In [1]:
eng_num = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']
kor_num = ['영', '일', '이', '삼', '사', '오', '육', '칠', '팔', '구']

numbers = {}
for i in range(len(eng_num)):
    for j in range(len(kor_num)):
        if i == j:
            numbers[i] = [eng_num[i], kor_num[j]]

print(numbers)

{0: ['zero', '영'], 1: ['one', '일'], 2: ['two', '이'], 3: ['three', '삼'], 4: ['four', '사'], 5: ['five', '오'], 6: ['six', '육'], 7: ['seven', '칠'], 8: ['eight', '팔'], 9: ['nine', '구']}

### 문제 02
아래 코드를 읽고 출력 결과를 맞춰보세요

In [2]:
car_data = [
    (2019, ['Toyota Camry', 'Honda Accord', 'Nissan Altima']),
    (2020, ['Toyota Corolla', 'Honda Civic', 'Nissan Sentra']),
    (2021, ['Toyota Avalon', 'Honda Insight', 'Nissan Maxima'])
]

car_dict = {}
for year, cars in car_data:
    car_list = []
    for car in cars:
        car_list.append(car)
    car_dict[year] = car_list

print(car_dict[2021])

['Toyota Avalon', 'Honda Insight', 'Nissan Maxima']

### 문제 03
아래 코드를 읽고 출력 결과를 맞춰보세요

In [15]:
sales_data = [
    {"month": "1월", "products": ["A", "B", "C"], "sales": [1000, 1200, 900]},
    {"month": "2월", "products": ["A", "B", "C"], "sales": [1100, 1300, 950]},
    {"month": "3월", "products": ["A", "B", "C"], "sales": [1050, 1250, 920]}
]

monthly_sales = {}

for data in sales_data:
    month = data["month"]
    product_sales = []
    for sale in data["sales"]:
        product_sales.append(sale)
    monthly_sales[month] = product_sales

print(monthly_sales)

{'1월': [1000, 1200, 900], '2월': [1100, 1300, 950], '3월': [1050, 1250, 920]}

### 문제 04
아래 코드를 읽고 출력 결과를 맞춰보세요

In [16]:
scores = [
    ['김하니', 85, 90, 95],
    ['박철수', 75, 80, 85],
    ['이유진', 90, 85, 95],
]

scores_dict = {}

for s in scores:
    name = s[0]
    individual_scores = []
    for score in s[1:]:
        individual_scores.append(score)
    scores_dict[name] = individual_scores

print(scores_dict)

{'김하니': [85, 90, 95], '박철수': [75, 80, 85], '이유진': [90, 85, 95]}

### 문제 05
아래 코드를 읽고 출력 결과를 맞춰보세요.
(아래 url은 존재하지 않는 가상의 url입니다.)

In [17]:
travel_links = {}

regions = {
    'Europe': ['Paris', 'Berlin', 'Rome'],
    'Asia': ['Tokyo', 'Seoul', 'Bangkok'],
    'North America': ['New York', 'Toronto', 'Mexico City']
}

for region, cities in regions.items():
    for city in cities:
        url = f"https://travel.example.com/{region.lower()}/{city.lower().replace(' ', '_')}"
        travel_links[city] = [url]

print(travel_links['Paris'])

['https://travel.example.com/europe/paris']

### 문제 06
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
data = [['Alice', 'Female', 25], ['Bob', 'Male', 32], ['Charlie', 'Male', 19]]

data_dict = {}
for row in data:
    name = None
    info_list = []
    for i, info in enumerate(row):
        if i == 0:
            name = info
        else:
            info_list.append(info)
    data_dict[name] = info_list

print(data_dict)

### 문제 07

In [ ]:
info = {'name': 'Jenny', 'age': 24, 'phone': '010-1234-5678', 'birth': '0807', 'email': 'jenny@gmail.com'}

new_info = {}

info_list = []
for key, value in info.items():
    for k in info:
        if key == k and k != 'name':
            info_list.append(value)

new_info[info['name']] = info_list

print(new_info)

### 문제 08
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
player_data = [
    {'name': 'Tom', 'Skills': 82, 'Strategy': 90, 'Teamwork': 88},
    {'name': 'Jerry', 'Skills': 78, 'Strategy': 84, 'Teamwork': 85},
    {'name': 'Anna', 'Skills': 90, 'Strategy': 85, 'Teamwork': 95}
]

player_scores = []
for player in player_data:
    name = player['name']
    scores = []
    for key, value in player.items():
        if key != 'name':
            scores.append(value)
    player_scores.append({'name': name, 'scores': scores})

print(player_scores[0])

### 문제 09
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
project_data = [
    {'project': 'Solar Power Efficiency', 'Efficiency': 75, 'Innovation': 80, 'Marketability': 70},
    {'project': 'AI for Healthcare', 'Efficiency': 85, 'Innovation': 95, 'Marketability': 90},
    {'project': 'Plastic Recycling', 'Efficiency': 65, 'Innovation': 75, 'Marketability': 80}
]

project_reviews = []
for project in project_data:
    title = project['project']
    scores = []
    for key, value in project.items():
        if key != 'project':
            scores.append(value)
    project_reviews.append({'project': title, 'scores': scores})

print(project_reviews[0])

### 문제 10
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
car_data = [{'model': 'Sedan', 'efficiency': 28, 'color': 'Blue'},
            {'model': 'SUV', 'efficiency': 22, 'color': 'Black'},
            {'model': 'Convertible', 'efficiency': 25, 'color': 'Red'}]

car_dict = []
for d in car_data:
    model = d['model']
    attributes = []
    for attribute in ['efficiency', 'color']:
        if attribute in d:
            attributes.append(d[attribute])
    car_dict.append({'model': model, 'attributes': attributes})

print(car_dict[0])

### 문제 11
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
score_data = [{'name': 'Alice', 'Math': 80, 'Science': 75, 'English': 90},
              {'name': 'Bob', 'Math': 90, 'Science': 85, 'English': 80},
              {'name': 'Charlie', 'Math': 85, 'Science': 90, 'English': 85}]

score_dict = []
for d in score_data:
    name = d['name']
    scores = []
    for subject in ['Math', 'Science', 'English']:
        if subject in d:
            scores.append(d[subject])
    avg_score = round((sum(scores) / len(scores)), 2)
    score_dict.append({'name': name, 'score': scores, 'avg_score': avg_score})

print(score_dict[0])

### 문제 12
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
review_data = [
    {'title': 'Interstellar', 'Acting': 85, 'Story': 90, 'Visuals': 95},
    {'title': 'The Godfather', 'Acting': 95, 'Story': 100, 'Visuals': 85},
    {'title': 'Avengers: Endgame', 'Acting': 80, 'Story': 85, 'Visuals': 100}
]

review_dict = []
for d in review_data:
    title = d['title']
    scores = []
    for category in ['Acting', 'Story', 'Visuals']:
        if category in d:
            scores.append(d[category])
    avg_score = round((sum(scores) / len(scores)), 2)
    review_dict.append({'title': title, 'score': scores, 'avg_score': avg_score})

print(review_dict[0])

### 문제 13
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
dataset = {'airplane': ['airplane_01.jpg', 'airplane_02.jpg', 'airplane_03.jpg'],
           'car': ['car_01.jpg', 'car_02.jpg', 'car_03.jpg']}

filepaths = {}

parent_path = '/content'

for category in dataset:
    filepaths[category] = []
    for filename in dataset[category]:
        filepaths[category].append(f'{parent_path}/{category}/{filename}')

print(filepaths['car'])

### 문제 14

아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
dataset = {
    'airplane': ['airplane_01.jpg', 'airplane_02.jpg', 'airplane_03.jpg'],
    'car': ['car_01.jpg', 'car_02.jpg', 'car_03.jpg'],
    'boat': ['boat_01.jpg', 'boat_02.png', 'boat_03.jpg']
}

selected_filepaths = {}

parent_path = '/content'

for category in dataset:
    selected_filepaths[category] = []
    for filename in dataset[category]:
        if filename.endswith('.jpg'):
            selected_filepaths[category].append(f'{parent_path}/{category}/{filename}')

print(selected_filepaths['airplane'])

### 문제 15
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
week_links = {}

weeks = ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun', 'dailyplus']
for week in weeks:
    url = f'https://comic.naver.com/webtoon/weekdayList?week={week}'
    if week != 'dailyplus':
        week_links[week] = [url]
    else:
        for day in ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun']:
            week_links[day].append(url)

print(week_links['mon'])

### 문제 16
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
eng_num = ['zero','one','two','three','four','five','six','seven','eight','nine']
kor_num = ['영','일','이','삼','사','오','육','칠','팔','구']

numbers = {}
for i, (eng, kor) in enumerate(zip(eng_num, kor_num)):
    numbers[i] = [eng, kor]

print(numbers)

### 문제 17
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
data = [
    {'company': 'TechCorp', 'Q1': 120000, 'Q2': 135000, 'Q3': 140000, 'Q4': 145000},
    {'company': 'HealthPlus', 'Q1': 80000, 'Q2': 85000, 'Q3': 90000, 'Q4': 95000},
    {'company': 'EcoFoods', 'Q1': 50000, 'Q2': 52000, 'Q3': 54000, 'Q4': 56000}
]

analysis = []
for company in data:
    yearly_revenue = sum(company[key] for key in company if key.startswith('Q'))
    growth_rate = ((company['Q4'] / company['Q1']) - 1) * 100
    analysis.append({
        'company': company['company'],
        'quarterly_revenue': [company['Q1'], company['Q2'], company['Q3'], company['Q4']],
        'yearly_revenue': yearly_revenue,
        'growth_rate': round(growth_rate, 2)
    })

print(analysis[0]['yearly_revenue'])

### 문제 18
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
dic_movies = {
    'director': [],
    'title': [],
    'rating': []
}

raw_dataset = {
    'movies': [
        'Christopher Nolan\\Inception\\8.8',
        'Martin Scorsese\\The Irishman\\7.9',
        'Quentin Tarantino\\Once Upon a Time in Hollywood\\7.6'
    ]
}

for movie_info in raw_dataset['movies']:
    parts = movie_info.split('\\')
    dic_movies['director'].append(parts[0])
    dic_movies['title'].append(parts[1])
    dic_movies['rating'].append(parts[2])

print(dic_movies['rating'])

### 문제 19
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
game_items = {
    'Sword': {'price': 100, 'damage': 20, 'weight': 5},
    'Shield': {'price': 50, 'defense': 15, 'weight': 10},
    'Potion': {'price': 30, 'healing': 10, 'weight': 1}
}


game_items_dict = {}
for item, value in game_items.items():
    price = value['price']
    damage = value['damage'] if 'damage' in value else 0
    defense = value['defense'] if 'defense' in value else 0
    healing = value['healing'] if 'healing' in value else 0
    weight = value['weight']
    game_items_dict[item] = [price, damage, defense, healing, weight]

print(game_items_dict['Sword'])

### 문제 20
아래 코드를 읽고 출력 결과를 맞춰보세요

In [ ]:
products = []

for name, price, stock, discount in [('Apple iPhone 14', 1299, 75, None), ('Samsung Galaxy S23', 1099, None, 45)]:
    product = {'name': name, 'price': price}
    if stock is not None:
        product['stock'] = stock
    else:
        product['stock'] = 0
    if discount is not None:
        product['discount'] = discount
    else:
        product['discount'] = 0
    products.append(product)

result = {}
for product in products:
    result[product['name']] = [product['price'], product['stock'], product['discount']]

print(result['Samsung Galaxy S23'])

## 쓰기 영역

### 문제 21
다음과 같은 동물과 품종에 대한 정보를 튜플 리스트로 표현한 'animal_data'가 있습니다.
```
animal_data = [
    ('Dog', 'Poodle'), ('Dog', 'Golden Retriever'), ('Dog', 'Labrador'),
    ('Cat', 'Siamese'), ('Cat', 'Persian'), ('Cat', 'Maine Coon'),
    ('Bird', 'Parrot'), ('Bird', 'Canary'), ('Bird', 'Finch')
]
```
- 반복문을 통해 animal_data를 순회하면서, animal_dict에 동물 종류를 키로 하고, 품종 목록을 값으로 추가합니다.
- 동물 종류가 딕셔너리에 존재하지 않으면 새로운 키를 생성하고 품종 리스트를 초기화합니다.
- 이미 존재하는 키에 대해서는 해당 동물의 품종을 리스트에 추가합니다.


```
# 출력 결과

{'Dog': ['Poodle', 'Golden Retriever', 'Labrador'], 'Cat': ['Siamese', 'Persian', 'Maine Coon'], 'Bird': ['Parrot', 'Canary', 'Finch']}

```

In [ ]:
animal_data = [
    ('Dog', 'Poodle'), ('Dog', 'Golden Retriever'), ('Dog', 'Labrador'),
    ('Cat', 'Siamese'), ('Cat', 'Persian'), ('Cat', 'Maine Coon'),
    ('Bird', 'Parrot'), ('Bird', 'Canary'), ('Bird', 'Finch')
]
animal_dict = {}

for animal, breed in animal_data:
        if animal not in animal_dict:
            animal_dict[animal] = []
        animal_dict[animal].append(breed)
print(animal_dict)

### 정답

In [ ]:
animal_data = [
    ('Dog', 'Poodle'), ('Dog', 'Golden Retriever'), ('Dog', 'Labrador'),
    ('Cat', 'Siamese'), ('Cat', 'Persian'), ('Cat', 'Maine Coon'),
    ('Bird', 'Parrot'), ('Bird', 'Canary'), ('Bird', 'Finch')
]

animal_dict = {}

for animal, breed in animal_data:
    if animal not in animal_dict: # 키값 조회
        animal_dict[animal] = []
    animal_dict[animal].append(breed)

print(animal_dict)

### 문제 22
다음과 같이 환율(exchange_rates)과 금액 정보(amounts)가 주어졌을 때,

금액 정보(amounts) 금액을 환전한 결과를 딕셔너리 형태로 저장하는 코드를 작성해보세요.
- 환전한 결과는 소숫점 첫째 자리까지 출력하세요.
- 단, 주어진 환율에 해당하는 통화가 없는 경우 딕셔너리에 키를 추가하고 값으로 None을 할당하세요.

```
# 출력 결과

{'USD': [1500000, 1348.5], 'EUR': [1250000, 922.5], 'JPY': [620000, 61249.8], 'CNY': [800000, None]}
```

In [ ]:
exchange_rates = {
    "USD": 0.000899,
    "EUR": 0.000738,
    "JPY": 0.09879,
}
amounts = [(1500000, "USD"), (1250000, "EUR"), (620000, "JPY"), (800000, "CNY")]

converted_amounts = {}
#환전한 결과는 소숫점 첫째 자리까지 출력하세요.
#단, 주어진 환율에 해당하는 통화가 없는 경우 딕셔너리에 키를 추가하고 값으로 None을 할당하세요.
for amount, currency in amounts:
    exchange_rate = exchange_rates.get(currency)
    if exchange_rate is not None:
        converted_amount =round(amount * exchange_rate, 1)
        converted_amounts[currency] = [amount, converted_amount]
    else:
        converted_amounts[currency] = [amount, None]
print(converted_amounts)

### 정답

In [ ]:
exchange_rates = {
    "USD": 0.000899,
    "EUR": 0.000738,
    "JPY": 0.09879,
}

amounts = [(1500000, "USD"), (1250000, "EUR"), (620000, "JPY"), (800000, "CNY")]

converted_amounts = {}

for amount, currency in amounts:
    exchange_rate = exchange_rates.get(currency)
    if exchange_rate is not None:
        converted_amount = round(amount * exchange_rate, 1)
        converted_amounts[currency] = [amount, converted_amount]
    else:
        converted_amounts[currency] = [amount, None]

print(converted_amounts)

### 문제 23
다음은 상품의 이름, 가격, 재고, 할인율, 무게의 순서로 상품 정보가 담긴 리스트입니다.

이 중에서 가격이 1,400,000 이상인 경우에만 해당 상품의 이름, 가격, 재고, 할인 및 무게를 result 딕셔너리에 저장하는 코드를 작성하세요.

```
products_list = [('WW10K6410QW', 1500000, 75, None, 0.15), ('WW80K52E38W', 1050000, None, 45, 0.3)]

```

In [ ]:
products_list = [('WW10K6410QW', 1500000, 75, None, 0.15), ('WW80K52E38W', 1050000, 45, None, 0.3)]

result = {}
for name, price, stock, discount, weight in products_list:
    if price >= 1400000:
        product = {'name': name, 'price': price}
        if stock is not None:
            product['stock'] = stock
        else:
            product['stock'] = 0
        if discount is not None:
            product['discount'] = discount
        else:
            product['discount'] = 0
        if weight is not None:
            product['weight'] = weight
        else:
            product['weight'] = 0
        result[name] = [price, product['stock'], product['discount'], product['weight']]
print(result)

### 정답

In [ ]:
products_list = [('WW10K6410QW', 1500000, 75, None, 0.15), ('WW80K52E38W', 1050000, None, 45, 0.3)]

result = {}
for name, price, stock, discount, weight in products_list:
    if price >= 1400000:
        product = {'name': name, 'price': price}
        if stock is not None:
            product['stock'] = stock
        else:
            product['stock'] = 0
        if discount is not None:
            product['discount'] = discount
        else:
            product['discount'] = 0
        if weight is not None:
            product['weight'] = weight
        else:
            product['weight'] = 0
        result[name] = [price, product['stock'], product['discount'], product['weight']]

print(result)

### 문제 24
개인의 정보를 딕셔너리로 변환하여 이름을 키로 사용하고, 해당 개인의 성별, 나이, 키, 몸무게를 값으로 가지는 리스트로 저장하는 코드를 작성해보세요.

```
data = [('Alice', 'F', 25, 165, 57 ),
        ('Bob', 'M', 32, 182, 78),
        ('Charlie', 'M', 19, 189, 70)]
```
출력 결과        
```
{'Alice': ['F', 25, 165, 57], 'Bob': ['M', 32, 182, 78], 'Charlie': ['M', 19, 189, 70]}
```

In [ ]:
data = [('Alice', 'F', 25, 165, 57 ),
        ('Bob', 'M', 32, 182, 78),
        ('Charlie', 'M', 19, 189, 70)]

data_dict = {}
keys = ['name', 'gender', 'age', 'height', 'weight']
ps_dict = {}

for d in data:
    for i, key in enumerate(keys):
        ps_dict[key] = d[i]
    data_dict[ps_dict['name']] = [ps_dict['gender'], ps_dict['age'], ps_dict['height'], ps_dict['weight']]

print(data_dict)

### 정답

In [ ]:
data = [('Alice', 'F', 25, 165, 57),
        ('Bob', 'M', 32, 182, 78),
        ('Charlie', 'M', 19, 189, 70)]

data_dict = {}
attribute_keys = ['name', 'gender', 'age', 'height', 'weight']

for person in data:
    person_dict = {}
    for i, key in enumerate(attribute_keys):
        person_dict[key] = person[i]
    data_dict[person_dict['name']] = [person_dict['gender'], person_dict['age'], person_dict['height'], person_dict['weight']]

print(data_dict)

### 문제 25
주어진 문자열 리스트에서 'e'를 포함하는 문자열과 포함하지 않는 문자열을 딕셔너리로 분류하는 코드를 작성해보세요.
- 딕셔너리: 'e'를 포함하는 문자열을 키 'has_e'에 저장하고, 포함하지 않는 문자열을 키 'no_e'에 저장하세요.
```
num = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']
```
출력 결과
```
{'no_e': ['two', 'four', 'six'], 'has_e': ['zero', 'one', 'three', 'five', 'seven', 'eight', 'nine']}
```

In [ ]:
num = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']

no_e = []
has_e = []

for n in num:
    found_e = False
    for char in n:
        if char == 'e':
            found_e = True
            break
    if found_e:
        has_e.append(n)
    else:
        no_e.append(n)
result = {'no_e' : no_e, 'has_e' : has_e}
print(result)

### 정답

In [ ]:
num = ['zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine']

no_e = []
has_e = []

for n in num:
    found_e = False
    for char in n:
        if char == 'e':
            found_e = True
            break
    if found_e:
        has_e.append(n)
    else:
        no_e.append(n)

result = {'no_e': no_e, 'has_e': has_e}

print(result)

### 문제 26
다음과 같이 지역별로 유명한 음식 데이터(specialty_data)가 주어졌을 때, 음식 이름을 기준으로 오름차순으로 정렬하는 코드를 작성해보세요.
```
specialty_data = [('Seoul', 'Kimchi'), ('Busan', 'Dwaeji Gukbap'), ('Jeju', 'Black Pork'),
                  ('Gyeongju', 'Hwangnam-ppang'), ('Gwangju', 'Mudeungsan Soju'),
                  ('Andong', 'Andong Soju'), ('Jeonju', 'Bibimbap'), ('Daejeon', 'Galbi'),
                  ('Gyeongsan', 'Chalboribbang'),('Sunchang', 'Gochujang'), ('Gyeongju', 'Gyeongju Bread')]
```                  


```
{'Andong': ['Andong Soju'], 'Jeonju': ['Bibimbap'], 'Jeju': ['Black Pork'], 'Gyeongsan': ['Chalboribbang'], 'Busan': ['Dwaeji Gukbap'], 'Daejeon': ['Galbi'], 'Sunchang': ['Gochujang'], 'Gyeongju': ['Hwangnam-ppang'], 'Seoul': ['Kimchi'], 'Gwangju': ['Mudeungsan Soju']}
```

### 정답

In [ ]:
# 특정음식 기준으로 정렬 (버블정렬)

specialty_data = [('Seoul', 'Kimchi'), ('Busan', 'Dwaeji Gukbap'), ('Jeju', 'Black Pork'),
                  ('Gyeongju', 'Hwangnam-ppang'), ('Gwangju', 'Mudeungsan Soju'),
                  ('Andong', 'Andong Soju'), ('Jeonju', 'Bibimbap'), ('Daejeon', 'Galbi'),
                  ('Gyeongsan', 'Chalboribbang'),('Sunchang', 'Gochujang'), ('Gyeongju', 'Gyeongju Bread')]


n = len(specialty_data)

for i in range(n):
    for j in range(i+1, n):
        if specialty_data[i][1] > specialty_data[j][1]:
            specialty_data[i], specialty_data[j] = specialty_data[j], specialty_data[i]

specialty_dict = {}

for special in specialty_data:
    specialty_dict[special[0]] = [special[1]]

print(specialty_dict)

### 문제 27
주어진 데이터는 자동차 브랜드와 그들의 모델명을 포함하고 있습니다.
```
car_data = [
    ('BMW', 'i8'), ('BMW', 'X5'), ('BMW', 'M4'), ('BMW', '3 Series'),
    ('Toyota', 'Prius'), ('Toyota', 'Camry'), ('Toyota', 'Corolla'), ('Toyota', 'Land Cruiser'),
    ('Ford', 'Mustang'), ('Ford', 'F-150'), ('Ford', 'Explorer'),
    ('Mercedes-Benz', 'S-Class'), ('Mercedes-Benz', 'G-Class'), ('Mercedes-Benz', 'E-Class'), ('Mercedes-Benz', 'C-Class'),
    ('Tesla', 'Model S'), ('Tesla', 'Model X'), ('Tesla', 'Model 3'), ('Tesla', 'Model Y')
]
```

이 데이터를 사용하여 각 브랜드별로 딕셔너리를 만들고, 각 브랜드에 속하는 모델명을 사전순으로 정렬하세요.

정렬 시에는 문자와 숫자가 섞여 있을 경우 숫자가 알파벳보다 앞에 오도록 정렬해야 합니다.

```
# 출력 결과

{'BMW': ['3 Series', 'i8', 'M4', 'X5'], 'Mercedes-Benz': ['C-Class', 'E-Class', 'G-Class', 'S-Class'], 'Toyota': ['Camry', 'Corolla', 'Land Cruiser', 'Prius'], 'Ford': ['Explorer', 'F-150', 'Mustang'], 'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y']}
```

### 정답

In [ ]:
car_data = [
    ('BMW', 'i8'), ('BMW', 'X5'), ('BMW', 'M4'), ('BMW', '3 Series'),
    ('Toyota', 'Prius'), ('Toyota', 'Camry'), ('Toyota', 'Corolla'), ('Toyota', 'Land Cruiser'),
    ('Ford', 'Mustang'), ('Ford', 'F-150'), ('Ford', 'Explorer'),
    ('Mercedes-Benz', 'S-Class'), ('Mercedes-Benz', 'G-Class'), ('Mercedes-Benz', 'E-Class'), ('Mercedes-Benz', 'C-Class'),
    ('Tesla', 'Model S'), ('Tesla', 'Model X'), ('Tesla', 'Model 3'), ('Tesla', 'Model Y')
]

n = len(car_data)

for i in range(n):
    for j in range(i + 1, n):
        if car_data[i][1] > car_data[j][1]:
            car_data[i], car_data[j] = car_data[j], car_data[i]

car_dict = {}

for brand, model in car_data:
    if brand in car_dict:
        car_dict[brand].append(model)
    else:
        car_dict[brand] = [model]

print(car_dict)

### 문제 28
다음과 같은 점수 데이터가 주어졌을 때, 총점을 기준으로 내림차순으로 데이터를 정렬하는 코드를 작성해보세요.
```
score_data = [{'name': 'Alice', 'Math': 80, 'Science': 75, 'English': 90},
              {'name': 'Bob', 'Math': 90, 'Science': 85, 'English': 80},
              {'name': 'Charlie', 'Math': 85, 'Science': 90, 'English': 85}]
```
            
```
# 출력 결과  

[{'name': 'Charlie', 'MSE_score': [85, 90, 85], 'total_score': 260}, {'name': 'Bob', 'MSE_score': [90, 85, 80], 'total_score': 255}, {'name': 'Alice', 'MSE_score': [80, 75, 90], 'total_score': 245}]
```

### 정답

In [ ]:
# 삽입 정렬
score_data = [{'name': 'Alice', 'Math': 80, 'Science': 75, 'English': 90},
              {'name': 'Bob', 'Math': 90, 'Science': 85, 'English': 80},
              {'name': 'Charlie', 'Math': 85, 'Science': 90, 'English': 85}]

score_dict = []
for d in score_data:
    name = d['name']
    scores = [d['Math'], d['Science'], d['English']]
    total_score = sum(scores)
    score_dict.append({'name': name, 'MSE_score': scores, 'total_score': total_score})

for i in range(len(score_dict)):
    max_idx = i
    for j in range(i+1, len(score_dict)):
        if score_dict[j]['total_score'] > score_dict[max_idx]['total_score']:
            max_idx = j
    score_dict[i], score_dict[max_idx] = score_dict[max_idx], score_dict[i]

print(score_dict)

### 문제 29
다음은 다양한 교통수단에 관련된 이미지 파일들을 담고 있는 데이터셋입니다.
```
dataset = {
    'airplane': ['airplane_01.jpg', 'airplane_02.jpg', 'airplane_03.jpg', 'airplane_04.jpg', 'airplane_05.jpg'],
    'car': ['car_01.jpg', 'car_02.jpg', 'car_03.jpg', 'car_04.jpg', 'car_05.jpg'],
    'bike': ['bike_01.jpg', 'bike_02.jpg', 'bike_03.jpg', 'bike_04.jpg', 'bike_05.jpg'],
    'train': ['train_01.jpg', 'train_02.jpg', 'train_03.jpg', 'train_04.jpg', 'train_05.jpg'],
    'boat': ['boat_01.jpg', 'boat_02.jpg', 'boat_03.jpg', 'boat_04.jpg', 'boat_05.jpg']
}
```

이 데이터셋을 사용하여 각 교통수단 카테고리에 해당하는 이미지 파일의 경로를 생성하여 딕셔너리 형태로 저장하는 코드를 작성하세요.

각 카테고리별로 모든 이미지 파일의 경로는 '/content/{카테고리명}/{이미지명}' 형식입니다.

```
# 출력 결과

{'airplane': ['/content/airplane/airplane_01.jpg', '/content/airplane/airplane_02.jpg', '/content/airplane/airplane_03.jpg', '/content/airplane/airplane_04.jpg', '/content/airplane/airplane_05.jpg'], 'car': ['/content/car/car_01.jpg', '/content/car/car_02.jpg', '/content/car/car_03.jpg', '/content/car/car_04.jpg', '/content/car/car_05.jpg'], 'bike': ['/content/bike/bike_01.jpg', '/content/bike/bike_02.jpg', '/content/bike/bike_03.jpg', '/content/bike/bike_04.jpg', '/content/bike/bike_05.jpg'], 'train': ['/content/train/train_01.jpg', '/content/train/train_02.jpg', '/content/train/train_03.jpg', '/content/train/train_04.jpg', '/content/train/train_05.jpg'], 'boat': ['/content/boat/boat_01.jpg', '/content/boat/boat_02.jpg', '/content/boat/boat_03.jpg', '/content/boat/boat_04.jpg', '/content/boat/boat_05.jpg']}
```

### 정답

In [ ]:
dataset = {
    'airplane': ['airplane_01.jpg', 'airplane_02.jpg', 'airplane_03.jpg', 'airplane_04.jpg', 'airplane_05.jpg'],
    'car': ['car_01.jpg', 'car_02.jpg', 'car_03.jpg', 'car_04.jpg', 'car_05.jpg'],
    'bike': ['bike_01.jpg', 'bike_02.jpg', 'bike_03.jpg', 'bike_04.jpg', 'bike_05.jpg'],
    'train': ['train_01.jpg', 'train_02.jpg', 'train_03.jpg', 'train_04.jpg', 'train_05.jpg'],
    'boat': ['boat_01.jpg', 'boat_02.jpg', 'boat_03.jpg', 'boat_04.jpg', 'boat_05.jpg']
}

paths = {}

for category, images in dataset.items():

    file_paths = []
    for image in images:
        full_path = f'/content/{category}/{image}'
        file_paths.append(full_path)

    paths[category] = file_paths

print(paths)

### 문제 30
다음은 요일별 작가, 제목, 별점 정보를 가진 딕셔너리입니다.

주어진 정보를 활용하여 요일별로 작가, 제목, 별점을 담은 딕셔너리를 만드는 코드를 작성해보세요.


```
raw_dataset = {
    'mon': ['김철수\\영구는못말려\\9.6', '하영진\\뽈롤로\\9.2', '신하영\\영구야놀자\\9.3'],
    'tue': ['홍길동\\타오르는청춘\\9.8', '이영희\\서른이지만열일곱입니다\\8.5', '이철수\\찬란하게떠오르는달\\9.1'],
    'wed': ['강감찬\\그해여름\\8.9', '조세호\\길에서\\9.0', '류현진\\빨간머리앤\\9.6'],
    'thu': ['김지원\\내일\\9.4', '김영수\\닥터프로스트\\8.7', '이영수\\나노리스트\\8.5'],
    'fri': ['김민수\\도깨비와도깨비사냥꾼\\9.2', '정희태\\제로게임\\8.8', '김재한\\파리의연인\\9.1'],
    'sat': ['신석기\\신의탑\\9.6', '하성운\\외모지상주의\\9.1', '유재석\\하이브3\\8.9'],
    'sun': ['박나래\\귀전구담\\9.3', '전우용\\더게임\\8.6', '박서준\\독립일기\\8.9']
}
```

출력 결과
```
{'author': {'mon': ['김철수', '하영진', '신하영'], 'tue': ['홍길동', '이영희', '이철수'], 'wed': ['강감찬', '조세호', '류현진'], 'thu': ['김지원', '김영수', '이영수'], 'fri': ['김민수', '정희태', '김재한'], 'sat': ['신석기', '하성운', '유재석'], 'sun': ['박나래', '전우용', '박서준']},   
'title': {'mon': ['영구는못말려', '뽈롤로', '영구야놀자'], 'tue': ['타오르는청춘', '서른이지만열일곱입니다', '찬란하게떠오르는달'], 'wed': ['그해여름', '길에서', '빨간머리앤'], 'thu': ['내일', '닥터프로스트', '나노리스트'], 'fri': ['도깨비와도깨비사냥꾼', '제로게임', '파리의연인'], 'sat': ['신의탑', '외모지상주의', '하이브3'], 'sun': ['귀전구담', '더게임', '독립일기']},   
'rating': {'mon': [9.6, 9.2, 9.3], 'tue': [9.8, 8.5, 9.1], 'wed': [8.9, 9.0, 9.6], 'thu': [9.4, 8.7, 8.5], 'fri': [9.2, 8.8, 9.1], 'sat': [9.6, 9.1, 8.9], 'sun': [9.3, 8.6, 8.9]}}
```

### 정답

In [ ]:
# 요일별 작가,제목,별점 담아보기

dic_toon = {
    'author': {'mon': [], 'tue': [], 'wed': [], 'thu': [], 'fri': [], 'sat': [], 'sun': []},
    'title': {'mon': [], 'tue': [], 'wed': [], 'thu': [], 'fri': [], 'sat': [], 'sun': []},
    'rating': {'mon': [], 'tue': [], 'wed': [], 'thu': [], 'fri': [], 'sat': [], 'sun': []}
}

raw_dataset = {
    'mon': ['김철수\\영구는못말려\\9.6', '하영진\\뽈롤로\\9.2', '신하영\\영구야놀자\\9.3'],
    'tue': ['홍길동\\타오르는청춘\\9.8', '이영희\\서른이지만열일곱입니다\\8.5', '이철수\\찬란하게떠오르는달\\9.1'],
    'wed': ['강감찬\\그해여름\\8.9', '조세호\\길에서\\9.0', '류현진\\빨간머리앤\\9.6'],
    'thu': ['김지원\\내일\\9.4', '김영수\\닥터프로스트\\8.7', '이영수\\나노리스트\\8.5'],
    'fri': ['김민수\\도깨비와도깨비사냥꾼\\9.2', '정희태\\제로게임\\8.8', '김재한\\파리의연인\\9.1'],
    'sat': ['신석기\\신의탑\\9.6', '하성운\\외모지상주의\\9.1', '유재석\\하이브3\\8.9'],
    'sun': ['박나래\\귀전구담\\9.3', '전우용\\더게임\\8.6', '박서준\\독립일기\\8.9']
}

for week, data in raw_dataset.items():
    for d in data:
        dic_toon['author'][week].append(d.split('\\')[0])
        dic_toon['title'][week].append(d.split('\\')[1])
        dic_toon['rating'][week].append(float(d.split('\\')[2]))

print(dic_toon)